Update README.md
ghmossi/TPN1_Curso_Embebidos_Mossi_Gabriel pull request #5
Opened 2024-08-15 23:34 UTC by ghmossi

Volví a crear un nuevo pull request. Saludos

2024-08-15 23:58 UTC, scaprile requested changes
Tomate tu tiempo y corregí todos los typos y faltas de acentos, por favor.
Esto se supone que es en cierto modo el equivalente a lo que le entregás a tu cliente para que te elija, o a tu gerente para que te apruebe el presupuesto.
No hace falta cerrar y volver a crear, hacé un commit con las correcciones

2024-08-16 19:56 UTC, scaprile requested changes
> todos los typos y faltas de acentos

2024-08-16 22:22 UTC, ghmossi commented
Perdón mi ignorancia, pero no entiendo cuando te referis a typos. ¿Estilos
de tipografía?

Saludos

El vie, 16 ago 2024 a las 16:56, Sergio R. Caprile (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> todos los typos y faltas de acentos
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ghmossi/TPN1_Curso_Embebidos_Mossi_Gabriel/pull/5#pullrequestreview-2243458766>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANJ3DVMSM62WJORHXYXDJQTZRZKOZAVCNFSM6AAAAABMTCJ5AGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBTGQ2TQNZWGY>
> .
> You are receiving this because you authored the thread.Message ID:
> <ghmossi/TPN1_Curso_Embebidos_Mossi_Gabriel/pull/5/review/2243458766@
> github.com>
>

2024-08-17 04:22 UTC, alutenberg commented
> Perdón mi ignorancia, pero no entiendo cuando te referis a typos. ¿Estilos de tipografía? Saludos 

https://www.google.com.ar/search?q=typos
https://www.google.com.ar/search?q=typos+examples

A few illustrative examples include: "now" instead of "not", "unclear" instead of "nuclear" "you" instead of "your"

2024-08-17 18:34 UTC, ghmossi commented
Todos los días se aprende algo nuevo. Repase varias veces el texto, no
encuentro más errores. Saludos

El sáb, 17 ago 2024 a las 1:22, alutenberg ***@***.***>)
escribió:

> Perdón mi ignorancia, pero no entiendo cuando te referis a typos. ¿Estilos
> de tipografía? Saludos
>
> https://www.google.com.ar/search?q=typos
> https://www.google.com.ar/search?q=typos+examples
>
> A few illustrative examples include: "now" instead of "not", "unclear"
> instead of "nuclear" "you" instead of "your"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ghmossi/TPN1_Curso_Embebidos_Mossi_Gabriel/pull/5#issuecomment-2294619417>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANJ3DVPWRDZ7T6HHG24HGELZR3FZLAVCNFSM6AAAAABMTCJ5AGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJUGYYTSNBRG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-18 10:56 UTC, alutenberg approved these changes
La propuesta está bien, queda aprobada. Fijate nomas de cambiar "WiFi" por "Wi-Fi" en todos lo casos, y que te quedó "5V" y debería ser "5 V".

2024-08-18 13:34 UTC, scaprile approved these changes

2024-08-18 13:34 UTC, scaprile commented on README.md
> +|Flujo basico|El usuario puede leer o escribir registros que mepean entradas y salidas, de esta manera puede manejar hardware.|
basico ? 1a persona del singular del verbo basicar ?

2024-08-18 13:34 UTC, scaprile commented on README.md
> +|Flujo basico|El usuario puede escribir un registro particular y el dato en el mismo será enviado por UART. Si el dato en el registro cambia, nuevamente se producirá un envió de información.|
convencimiento o copy-paste ?

2024-08-18 13:35 UTC, scaprile commented
> no encuentro más errores

yo sí, pero sólo porque es tu trabajo y no uno mío... :wink:

2024-08-19 03:59 UTC, ghmossi commented on README.md
> +|Flujo basico|El usuario puede escribir un registro particular y el dato en el mismo será enviado por UART. Si el dato en el registro cambia, nuevamente se producirá un envió de información.|
solo copy-paste el formato del informe, lo demás puro convencimiento.

2024-08-29 02:56 UTC, merged